### ISSUE TITLE
鸿蒙系统如何获得db

### ISSUE THREAD

**Issue by xiaoyuesansui** [lqzhgood/Shmily-Get-Wechat#1]
hello 楼主
目前我用的手机是p30pro ，鸿蒙3系统，未root
通过系统备份拿到了 
com.tencent.mm.tar
com.tencent.mm.apk

.tar 文件根本解不出来，file 看文件类型就是 ：data

看了些资料发现有人提出会有 tar 打包，但是没说解压的方法

请问这个情况该如何应对

**Comment by lqzhgood** [comment]
由于我没有华为手机，无法进行测试

看这里说 https://zhuanlan.zhihu.com/p/61885338 貌似 .tar 可以直接解压，你试试 7z 和 winrar

我更新了文档，罗列了一个更通用的方式：
你可以通过 安卓虚拟机/模拟器 获取 db， 因为大部分 安卓虚拟机/模拟器 都自带 root~
https://github.com/lqzhgood/Shmily-Get-Wechat-Android/tree/main/export/db-android/1%20decode%20db

**Comment by xiaoyuesansui** [comment]
我说bandizip，会直接报解压缩失败，类型未知
晚点我试试7z和winrar

**Comment by lqzhgood** [comment]
我找到了这篇文章 https://1248.ink/?p=8 ，貌似可行
你试试~

**Comment by xiaoyuesansui** [comment]
多谢 我试试 
因为我用的是一个两年前的老备份，可能还真是备份的时候输入了密码  导致了加密
