### ISSUE TITLE
可否支持一次解密所有的对话

### ISSUE THREAD

**Issue by ppBruce** [lqzhgood/Shmily-Get-Wechat#3]
不知理解是否对，目前的dbToJson需要指定talker后修改config.js，每次解密一个对话。
能否有批量解密所有对话的方式？

**Comment by lqzhgood** [comment]
自己写个批处理就行了吧~

const list = ["t1","t2","t3"....]

``` 
// 思路

for (let i= 0; index < list ; i++) {
      1. 修改 config.js
      2. 执行 npm run build
      3. 重命名 dist
}
```

**Comment by lqzhgood** [comment]
或者里这里直接返回 true

https://github.com/lqzhgood/Shmily-Get-Wechat/blob/d38950bb35ffe1130459831e2bc7051f8e01c0d5/export/db-android/2%20dbToJson/index.js#L23-L25
