### ISSUE TITLE
视频号 需要数据支持

### ISSUE THREAD

**Issue by lqzhgood** [lqzhgood/Shmily-Get-Wechat#6]
@hitech-h 

更新一下 Shmily-Get-Wechat 和 Shmily-Show 的代码, 注意更新代码的时候不要覆盖自己的 config.js

数据正常导出后

1. 在 Shmily-Show 中过滤出 `微信` 的 `视频号`, 
2. 按 F12 打开控制台, 
3. 任意 `视频号` 消息的头像上点右键选择 `F12 打印详细`
4. 在控制台中复制 Object 发给我

**Comment by hitech-h** [comment]
已收到，下周拿到电脑就开始

**Comment by hitech-h** [comment]
已发至邮箱

**Comment by lqzhgood** [comment]
你更新了 `Shmily-Get-Wechat` 的代码吗?

我看到你发给我的消息 内容是 "未知类型",

**Comment by hitech-h** [comment]
是最新的哦，用的第三方工具下载
<img width="509" alt="屏幕截图 2023-11-19 134342" src="https://github.com/lqzhgood/Shmily-Get-Wechat/assets/137307061/6cd1c96b-2925-402c-b597-3ac07c4cf76d">

在`dbToJson`和`ToMsg`都导出的是单个好友的数据
在`ToMsgNew\dist\Wechat-wxid_1234567890abcd-20230902.json`也显示未知类型

**Comment by lqzhgood** [comment]
我知道了, 是一种新的 "视频号" 格式~~  =.=!

**Comment by lqzhgood** [comment]
可以了~ 更新一下 `ToMsg\convert\android\typeMap.js` 就行了

这条消息在你微信中是正常显示的吧? 

我这里视频号的数据里面都有一行 `当前微信版本不支持展示该内容，请升级至最新版本。` 但明明是正常显示的,  所以我看看你那边的数据是不是也显示这一行  (果然一样)


可能这句话是微信做的兼容处理吧.
